[package]
name = "mofl"
version = "0.1.0"
authors = ["Ratchaphon Manosuthi <themelo64@gmail.com>"]

[dependencies]
chrono = "0.4"
serde = "1.0.82"
zip = "0.5.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_18"] # Minimum target 3.18 (Ubuntu 16.04 LTS)

[dependencies.gio]
version = "0.5.1"